### ISSUE TITLE
thread 'main' panicked at 'index out of bounds when using crossterm as the backend

### ISSUE THREAD

**Issue by aimerib** [amethyst/bracket-lib#257]
I've been unable to use crossterm as my backend for bracket-lib, getting a compile error even when trying one of the examples.

I initially thought that this issue could be related to #256 but that issue seems specifically about how to get bracket to use crossterm instead of a opengl window, so I'm opening an issue for my specific error.

This is my minimal setup that seems to be able to reproduce my issue:

rustup toolchain: stable-x86_64-unknown-linux-gnu (default)
rustc version: rustc 1.57.0 (f1edd0429 2021-11-29)
cargo version: cargo 1.57.0 (b2e52d7ca 2021-10-21)
Linux kernel: Linux 5.13.0-27-generic x86_64
Ubuntu version: Ubuntu 21.10 Iimpish Idri
$TERM: xterm
Shell: zsh

Cargo.toml
```toml
[package]
name = "bracket-test"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
bracket-terminal = { git = "https://github.com/amethyst/bracket-lib.git", version = "0.8.1", default-features = false, features = ["cross_term"] }
legion = { version = "0.4.0", default-features = false, features = ["wasm-bindgen"] }
lazy_static = "1.4.0"
```

sample main.rs to reproduce:
```rust
use bracket_terminal::prelude::*;

bracket_terminal::add_wasm_support!();

struct State {}

impl GameState for State {
    fn tick(&mut self, ctx: &mut BTerm) {
        ctx.print(1, 1, "Hello Bracket World");
    }
}

fn main() -> BError {
    let context = BTermBuilder::simple80x50()
        .with_title("Hello Minimal Bracket World")
        .build()?;

    let gs: State = State {};

    main_loop(context, gs)
}

```
Note: The above code is a copy paste from the hello_minimal.rs

The error I get is this:
```
cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/bracket-test`
thread 'main' panicked at 'index out of bounds: the len is 1840 but the index is 3920', /home/user/.cargo/git/checkouts/bracket-lib-bcfc6f411b633b6a/5e35a05/bracket-terminal/src/hal/crossterm_be/main_loop.rs:233:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
and the full backtrace:
```
Finished dev [unoptimized + debuginfo] target(s) in 0.05s                                                                                                                                                                                                   Running `target/debug/bracket-test`
thread 'main' panicked at 'index out of bounds: the len is 1840 but the index is 3920',
  /home/user/.cargo/git/checkouts/bracket-lib-bcfc6f411b633b6a/5e35a05/bracket-terminal/src/hal/crossterm_be/main_loop.rs:233:25                                                   
stack backtrace:                                                                                                 
  0: rust_begin_unwind at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
  1: core::panicking::panic_fmt at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
  2: core::panicking::panic_bounds_check at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:76:5
  3: <usize as core::slice::index::SliceIndex<[T]>>::index_mut at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/slice/index.rs:190:14
  4: core::slice::index::<impl core::ops::index::IndexMut<I> for [T]>::index_mut at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/slice/index.rs:26:9
  5: <alloc::vec::Vec<T,A> as core::ops::index::IndexMut<I>>::index_mut at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/vec/mod.rs:2508:9
  6: bracket_terminal::hal::crossterm_be::main_loop::full_redraw at /home/aimeri/.cargo/git/checkouts/bracket-lib-bcfc6f411b633b6a/5e35a05/bracket-terminal/src/hal/crossterm_be/main_loop.rs:233:25
  7: bracket_terminal::hal::crossterm_be::main_loop::main_loop sterm_be/main_loop.rs:140:34                     
  8: bracket_terminal::bterm::main_loop at /home/aimeri/.cargo/git/checkouts/bracket-lib-bcfc6f411b633b6a/5e35a05/bracket-terminal/src/bterm.rs:1083:5
  9: bracket_test::main at ./src/main.rs:43:5          
  10: core::ops::function::FnOnce::call_once at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
so it seems like on line 233 of main_loop.rs for crossterm_be this line is called:
```rust
buffer[buf_idx].glyph = to_char(t.glyph as u8);
```
which means that `buffer.len() == 1840` and `buf_idx == 3920`. 
seems like buf_idx is calculated by this line
```rust
let mut buf_idx = (st.height as u16 - (y as u16 + 1)) as usize * width as usize;
```
on my machine the values from width and height are as follow when executing my application:
```
st.height == 50
st.width == 80
width == 190
height == 50

I'm glad to help troubleshoot this in any way I can, so feel free to ask for any additional information I can provide to help troubleshoot. I'm not afraid to jump in to the code in the library to get some debug outputs as well, so if that's helpful in anyway let me know.

**Comment by aimerib** [comment]
just another bit of info, the exact same error happens if I try to run the example hello_minimal with
```
cargo run --no-default-features --features cross_term --example hello_minimal
```

**Comment by thebracket** [comment]
That's kinda odd; I tried it on my windows setup, and the crossterm back-end resized my terminal to match the requested size. So the actual width & height match the requested dimensions. It looks like I'm happily assuming that the resize worked - resizing the window after it's running crashes it.

I'll see what I can come up with.

**Comment by thebracket** [comment]
The fix I just pushed takes care of the problem on my end. My testing options are a bit limited right now (I'm work-from-home with a newborn baby) - so I can't currently get to my Linux & Mac test boxes.

**Comment by aimerib** [comment]
Thank you so much for the fast reply, and congratulations on your new child! I find myself in a very similar situation, working from home with a 5mo baby, so I understand the struggle and appreciate the effort.

Alas, this didn't fix it for me. Now the buffer size and the buffer_idx always have the same size, which after lines 239 and 317 will always be one higher than the length of the buffer vector, therefore causing the next run of the loop to crash with an out of bounds again.

Since you mentioned this is working for you (on Windows I assume? wsl2 or cgywin?) I will do some more digging on my end to see if I can figure out why the discrepancies. It will take me some time as I have to setup a vm for this. I will also test it on a Mac to see if the behavior is any different. I will also try on a simple ubuntu vm with a fresh install to rule out any weirdness with whatever I might have installed in my system.

Just some extra behavioral information I thought was interesting:
When I subtracted 1 from the initial buf_idx (to account for the fact that it is now created with the same size as the buffer itself) and reduce the buffer_idx at the end of the loop instead of increase, bracket-terminal compiles just fine, but the resulting console would only cover 2/5 of my screen (on the left side?).
I don't think the above is related to the root issue, but it was nice to see I could at least get something on the screen.

Just for my own edification, why do we want the buf_id to be the same size as the buffer, instead of starting from 0 and increasing it with each iteration of the for loops until it reaches the size of the buffer?

**Comment by thebracket** [comment]
I should be able to take another look tomorrow. The backing buffer index is calculated with the terminal size, while the size of a console may not be exactly the same (sometimes you request a size and the window manager helpfully hands you another one, or the application is assuming a fixed size and we've ruined its day by resizing). So we calculate the index based on the console's coordinates - which might not be the same. I'm beginning to question my logic; I should be able to give this a good once-over tomorrow.

**Comment by MichaelMackus** [comment]
@thebracket any ideas on this? I'm also getting this same error trying to use crossterm

**Comment by MichaelMackus** [comment]
Also, I did just try the backend = "cross_term" on one of the examples in the git master and it works fine. So far I am consistently getting this failure in bracket-lib v0.8.7

**Comment by MichaelMackus** [comment]
Strangely, I did just try the backend = "cross_term" on one of the examples in the git master and it works fine. Maybe this is only failing if you don't use bracket_terminal directly?

**Comment by sdsalyer** [comment]
Apologies for digging this back up, but I wanted to share / ask question.

I was encountering the same issue with the index out of bounds panic and eventually narrowed it down to a line of code from the *Hands-on Rust* book that's used to scale the topmost layer of the UI:

```rust
 fn main() -> BError {
     let context = BTermBuilder::new()
         .with_title("Dungeon Crawler")
         .with_fps_cap(30.0)
         .with_dimensions(DISPLAY_WIDTH, DISPLAY_HEIGHT)
         .with_tile_dimensions(32, 32)
         .with_resource_path("resources/")
         .with_font("dungeonfont.png", 32, 32)
         .with_font("terminal8x8.png", 8, 8)
         .with_simple_console(DISPLAY_WIDTH, DISPLAY_HEIGHT, "dungeonfont.png")
         .with_simple_console_no_bg(DISPLAY_WIDTH, DISPLAY_HEIGHT, "dungeonfont.png")

        // -------------------------------------------- 
         .with_simple_console_no_bg(SCREEN_WIDTH*2, SCREEN_HEIGHT*2, "terminal8x8.png")
        // -------------------------------------------- 

         .build()?;¬
 
     main_loop(context, State::new())¬
 }
```
`SCREEN_WIDTH*2, SCREEN_HEIGHT*2` -- the `crossterm` backend doesn't care for this at all.


I don't quite follow why in the crossterm main_loop it is getting MIN of `SimpleConsole` height vs. crossterm height and then subtracting that from the SimpleConsole height  to determine the buffer index?

https://github.com/amethyst/bracket-lib/blob/6117297503e117088069e317945b1f066c1048cd/bracket-terminal/src/hal/crossterm_be/main_loop.rs#L179-L197

## My hacky workaround

What I ended up doing was adding the `crossterm` crate to my project and using it to query the terminal width and height, and set all the values accordingly (i.e. *not* multiplying the width and height) -- then I end up with a nice full-screen application. Although it does seem to be off by a couple of pixels on the right and bottom margins?

 There are a couple other problems with this:

1. closing the application (`<Ctl-C>`) doesn't clean up the terminal completely. The area used by the bracket console will remain with black background, though raw mode seems to have been exited at least -- still, you must type in `reset` to get the colors back in order.


My code solution for avoiding that was to use my own setup / teardown using `crossterm` to call before/after the bracket setup and main loop (I realize this is partly redundant with bracket-terminal entering raw mode, etc., but crossterm doesn't seem to worry about that).

```rust
fn term_setup() {
    queue!(
        std::io::stdout(),
        // These features could be overkill -- whatever added needs to be removed in teardown
        EnableBracketedPaste,
        EnableFocusChange,
        EnableMouseCapture,
        cursor::Hide,
        EnterAlternateScreen
    )
    .expect("Should set up terminal");

    queue!(std::io::stdout(), terminal::Clear(terminal::ClearType::All))
        .expect("should clear screen");

    terminal::enable_raw_mode().expect("should enable raw mode");
}

fn term_teardown() {
    // terminal cleanup
    queue!(
        std::io::stdout(),
        ResetColor,
        DisableBracketedPaste,
        DisableFocusChange,
        DisableMouseCapture,
        cursor::Show,
        LeaveAlternateScreen
    )
    .expect("Should reset terminal");

    terminal::disable_raw_mode().expect("Should exit raw mode");

    queue!(
        std::io::stdout(),
        terminal::Clear(terminal::ClearType::Purge)
    )
    .expect("Should clear terminal")
}

```

1. b. any panic in the application (e.g. the index out of bounds discussed above) leaves the terminal in raw mode and again one must blindly type in `reset` to get it back in order. I think this should probably be better handled in bracket-terminal. There's probably some way I can detected that panic in my code and clean up the terminal similarly, but I'm not sure how to do that right off.



2. Layers don't seem to work with `crossterm` backend, or I'm not setting it up right? I merely wanted to take my completed game from the *Hands-on Rust* book and switch it over to using `crossterm` so it can [ultimately] be rendered in a terminal as a door game for a BBS. In any case, I will end up seeing the health bar (i.e. the top layer) and nothing else:

<img width="927" height="1053" alt="Image" src="https://github.com/user-attachments/assets/6cecb0af-362a-41d0-8821-82ea520e7eec" />

If I disable the hud layer and comment out the addition of that console in the builder, I can see my `@` and other entities on the screen (if I can find them) but no map.  Likewise, if I disable the entity render system and its layer, I can see the map (at least, my player's FoV) and run around until an unseen entity destroys me.

So, it seems the background isn't "transparent" even when the console is set up with `*_no_bg` ?  I tried replacing my background colors with an alpha value (e.g. `(0, 0, 0, 0)`) but this didn't help, either or I somehow botched it.

```rust
fn main() -> BError {
    const USE_GUI: bool = false;
    const FONT_TILE: (&str, i32, i32) = ("dungeonfont.png", 32, 32);
    const FONT_TEXT: (&str, i32, i32) = ("terminal8x8.png", 8, 8);
    let (width, height): (i32, i32);

    if !USE_GUI {
        // Use terminal
        term_setup();

        let (w, h) = terminal::size().expect("Should have gotten terminal dimensions.");
        width = w as i32;
        height = h as i32;
        println!("Got terminal dimensions: {}w x {}h", w, h);
    } else {
        (width, height) = (DISPLAY_WIDTH, DISPLAY_HEIGHT);
        println!("Got GUI dimensions: {}w x {}h", width, height);
    }

    if width < DISPLAY_WIDTH || height < DISPLAY_HEIGHT {
        panic!(
            "Terminal too small. Must be {} x {}",
            DISPLAY_WIDTH, DISPLAY_HEIGHT
        );
    }

    let mut bldr = BTermBuilder::new()
        .with_title("R O G U !")
        .with_fps_cap(30.0)
        // .with_fullscreen(true)
        // .with_fitscreen(true)
        // .with_tile_dimensions(24, 24)
        .with_dimensions(width, height)
        .with_tile_dimensions(32, 32)
        .with_resource_path("resources/")
        .with_font(FONT_TILE.0, FONT_TILE.1, FONT_TILE.2)
        .with_font(FONT_TEXT.0, FONT_TEXT.1, FONT_TEXT.2)
        .with_simple_console(width, height, FONT_TILE.0) // layer 0
        .with_simple_console_no_bg(width, height, FONT_TILE.0) // layer 1
        ;

    if !USE_GUI {
        bldr = bldr
            .with_vsync(false)
            .with_simple_console_no_bg(width, height, FONT_TEXT.0); // layer 2
    } else {
        bldr = bldr.with_simple_console_no_bg(SCREEN_WIDTH * 2, SCREEN_HEIGHT * 2, FONT_TEXT.0); // layer 2
    }

    let context = bldr.build()?;
    let ret_val = main_loop(context, State::new());

    if !USE_GUI {
        term_teardown();
    }

    ret_val
}
```

## Cries for help

So, am I barking up the wrong tree thinking I can just swap one backend for another with minimal headache? I want to get the ASCII / ANSI / CP437 version of a rogue-like game working in a terminal one way or another, if I have to swap out bracket's main loop or rendering for my own crossterm implementation, I can try to move in that direction. In any case, I would appreciate some guidance if anyone has any input. :)
